language: python
dist: trusty
branches:
  only:
  - master
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements/test.txt
  - pip install -e .
  - python -c 'import pkg_resources; print("export MOPROFILER_VERSION={}".format(pkg_resources.get_distribution("moprofiler").version))' > VERSION && source VERSION
addons:
  sonarcloud:
    organization: "littlemo-github"
before_script:
  - git fetch --unshallow
script:
  - pytest --cov=source/moprofiler --cov-branch --cov-report=xml:reports/coverage.xml -s tests
  - pytest --cov=source/moprofiler --cov-branch --cov-report=xml:reports/coverage.xml --cov-append -s 'tests/test_50_time_profiler_mixin.py::TestTimeProfilerMixin::test_time_profiler_key_error'
  - pytest --cov=source/moprofiler --cov-branch --cov-report=xml:reports/coverage.xml --cov-append -s 'tests/test_50_time_profiler_to_function.py::TestTimeProfilerToFunction::test_time_profiler_call'
  - coverage report -m
after_success:
  - sonar-scanner -Dsonar.projectVersion=${MOPROFILER_VERSION}
deploy:
  provider: pypi
  on:
    tags: true
  distributions: "bdist_wheel"
  skip_existing: true
  user: "moore"
  password:
    secure: iUN0pLADgbH3ZFCcaG3K8iBhFYCNTOUOYYQRpoWR6IDtTRoPA3Y7Pu4IGJqwOPRGbZe7XDLdNpcyonj1maTBdQ6yof+/Fbn6zsXfCOYJ9wKwHUUTmXKulq/+qSTdLBmml/eCEh/4gobdQsAAzm3x0DQ/MbV2zCI2dGiC9CXBERQ5EjlW/ekK7QaxGWgLaGEKOEGoIbjGnHV/KZYOt5wgZhL68mkrXnlYjrN3PhMqA52zienEFVJ+N82BiZ0JdX65TGR/p6cNVOVTPMw6YItKqbENhWGoI+vB/cvHBbpedSETTaihrTTkeMPJNFiz1L28qivVDQ71Hm7lD3aNspcOjhTNOBO/oo0EvqKmyqkff4PLOQhwgDr1ih8vTCxZA/Fy/OTaqrrjZ0NBQli99+gkI6V7TcPYKUZNbrV6FA+cFQetnf43qvlCC7JwM+UVc3D9Tg9AHHd46sZ+ZIO7oFrxlUMYsyPS8d3pJ/Vz/XMitcfQgoKPPhZ+TTAV6OfkQq/Oe5rI7nH/+SNsjWrilKCHQfcaFz2TNxF7ga4N5CfHj1TMrgOBmm/uhbXBEp8tRmiSLgi3tPyKCascHnhMmakw3G9ZxqWMiPmSj46IhjfB4BS7ndttlLw4ZFo2joltwHx+TlogW2WGkDB5AzwNG537oU6IJKd3n94GaaCYGSOGxHg=
