language: python
dist: trusty
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements/test.txt
  - pip install -e .
  - python -c 'import os, pkg_resources; os.environ["MOPROFILER_VERSION"] = pkg_resources.get_distribution("moprofiler").version'
addons:
  sonarcloud:
    organization: "littlemo-github"
before_script:
  - git fetch --unshallow
script:
  - pytest --cov=source/moprofiler --cov-branch --cov-report=xml:reports/coverage.xml -s tests
  - pytest --cov=source/moprofiler --cov-branch --cov-report=xml:reports/coverage.xml --cov-append -s 'tests/test_50_time_profiler_mixin.py::TestTimeProfilerMixin::test_time_profiler_key_error'
  - pytest --cov=source/moprofiler --cov-branch --cov-report=xml:reports/coverage.xml --cov-append -s 'tests/test_50_time_profiler.py::TestTimeProfiler::test_time_profiler'
  - coverage report -m
after_success:
  - sonar-scanner -Dsonar.projectVersion=${MOPROFILER_VERSION}
